### ISSUE TITLE
Pause Button

### ISSUE THREAD

**Issue by jordode** [jordode/Chibi-Knight-2-The-Better-Version#6]
Develop Pause Button

- [x] Research tutorials or other resources to see how a pause button is implemented
- [x] Develop code for pause button
- [x] Test pause button
- [x] Paste code into comments

**Comment by ImBoredHelp** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PauseGame : MonoBehaviour {
    public Transform canvas2;
    public Transform Player;


	// Update is called once per frame
	void Update () {
		if(Input.GetKeyDown(KeyCode.Escape))
        {
            Pause();
        }
	}
    public void Pause()
    {
        if (canvas2.gameObject.activeInHierarchy == false)
        {
            canvas2.gameObject.SetActive(true);
            Time.timeScale = 0;
        }
        else
        {
            canvas2.gameObject.SetActive(false);
            Time.timeScale = 1;
        }
    }
}

**Comment by ImBoredHelp** [comment]
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PauseGame : MonoBehaviour {
    public Transform canvas2;
    public Transform Player;


	// Update is called once per frame
	void Update () {
		if(Input.GetKeyDown(KeyCode.Escape))
        {
            Pause();
        }
	}
    public void Pause()
    {
        if (canvas2.gameObject.activeInHierarchy == false)
        {
            canvas2.gameObject.SetActive(true);
            Time.timeScale = 0;
        }
        else
        {
            canvas2.gameObject.SetActive(false);
            Time.timeScale = 1;
        }
    }
}`

**Comment by atartz10** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PauseGame : MonoBehaviour
{
    public Transform Canvas;
    public Transform PauseMenu;
    public Transform soundsMenu;
    public Transform videoSettingsMenu;
    public Transform controlsMenu;
    public Transform Player;


    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            Pause();
        }
    }
    public void Pause()
    {
        if (Canvas.gameObject.activeInHierarchy == false)
        {
            if (PauseMenu.gameObject.activeInHierarchy == false)
            {
                PauseMenu.gameObject.SetActive(true);
                soundsMenu.gameObject.SetActive(false);
                videoSettingsMenu.gameObject.SetActive(false);
                controlsMenu.gameObject.SetActive(false);
            }
            Canvas.gameObject.SetActive(true);
            Time.timeScale = 0;
        }
        else
        {
            Canvas.gameObject.SetActive(false);
            Time.timeScale = 1;
        }
    }

    public void Sounds(bool Open)
    {
        if (Open)
        {
            soundsMenu.gameObject.SetActive(true);
            PauseMenu.gameObject.SetActive(false);
        }
        if (!Open)
        {
            soundsMenu.gameObject.SetActive(false);
            PauseMenu.gameObject.SetActive(true);
        }
    }


    public void Graphics(bool Open)
    {
        if (Open)
        {
            videoSettingsMenu.gameObject.SetActive(true);
            PauseMenu.gameObject.SetActive(false);
        }
        if (!Open)
        {
            videoSettingsMenu.gameObject.SetActive(false);
            PauseMenu.gameObject.SetActive(true);
        }
    }


    public void Controls(bool Open)
    {
        if (Open)
        {
            controlsMenu.gameObject.SetActive(true);
            PauseMenu.gameObject.SetActive(false);
        }
        if (!Open)
        {
            controlsMenu.gameObject.SetActive(false);
            PauseMenu.gameObject.SetActive(true);
        }
    }
}
